/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aibreakthroughchessgame;

import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class Chess extends javax.swing.JPanel implements HintItem {
    private int BoardIndex;
    private Controler control;
    private boolean Focus = false;
    private int ChessType;
    private boolean Hint = false;
    private JLabel[] chessImage  ;
    private JLabel[] HintImage   ;
    /**
     * Creates new form Chess
     */
    public Chess(Controler control,int ChessType) {
        this.ChessType =  ChessType ;
        this.control = control;
        initComponents();
        setUpImage();
        unVisibleAll();
        chessImage[ChessType].setVisible(true);
        this.setVisible(true);
    }
    private void setUpImage(){
        JLabel[] chessImage  = {null,White,Black};
        this.chessImage = chessImage;
        JLabel[] HintImage   = {null,WhiteHint,BlackHint};
        this.HintImage = HintImage;
    }
    public int getType(){
        return this.ChessType;
    }
    public void setBoardIndex(int Index){
        this.BoardIndex = Index;
    }
    public int getIndex(){
        return this.BoardIndex;
    }
    public boolean tryFocus(){
        return this.Focus ;
    }
    public void Focus(){
        this.Focus = true;
    }
    public void unFocus(){
        this.Focus = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        White = new javax.swing.JLabel();
        Black = new javax.swing.JLabel();
        BlackHint = new javax.swing.JLabel();
        WhiteHint = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        White.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibreakthroughchessgame/whitePawn.jpg"))); // NOI18N
        White.setText("jLabel1");

        Black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibreakthroughchessgame/BlachPawn.jpg"))); // NOI18N
        Black.setText("jLabel1");

        BlackHint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibreakthroughchessgame/BlackPawnHint.jpg"))); // NOI18N
        BlackHint.setText("jLabel1");
        BlackHint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlackHintMouseClicked(evt);
            }
        });

        WhiteHint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibreakthroughchessgame/WhitePawnHint.jpg"))); // NOI18N
        WhiteHint.setText("jLabel1");
        WhiteHint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WhiteHintMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(White, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BlackHint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Black, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(WhiteHint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(White)
            .addComponent(BlackHint)
            .addComponent(Black)
            .addComponent(WhiteHint)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        this.control.unFocusChess();
        this.control.FocusChess(this);
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 100, 100), 3));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
    }//GEN-LAST:event_formMouseExited

    private void WhiteHintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WhiteHintMouseClicked
        // TODO add your handling code here:
        TryCapure();
    }//GEN-LAST:event_WhiteHintMouseClicked

    private void BlackHintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlackHintMouseClicked
        // TODO add your handling code here:
        TryCapure();
    }//GEN-LAST:event_BlackHintMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Black;
    private javax.swing.JLabel BlackHint;
    private javax.swing.JLabel White;
    private javax.swing.JLabel WhiteHint;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hint() {
        this.Hint = true;
        this.unVisibleAll();
        this.HintImage[this.ChessType].setVisible(true);
    }
    private void TryCapure(){
        if(this.Hint){
            this.control.PlayerMove(BoardIndex);
            //this.control.remove(this);
            this.setVisible(false);
        }
        this.control.unFocusChess();
    }
    
    

    @Override
    public void unhint() {
        this.Hint = false;
        this.unVisibleAll();
        this.chessImage[this.ChessType].setVisible(true);
    }

    @Override
    public boolean tryHint() {
        return this.Hint;
    }
    private void unVisibleAll(){
        this.Black.setVisible(false);
        this.BlackHint.setVisible(false);
        this.White.setVisible(false);
        this.WhiteHint.setVisible(false);
    }
}
